// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSPDSOc0qnZbRakxJluaLqK7-xD0w1tiM',
    appId: '1:373638168139:web:0f97644c476558c06017ce',
    messagingSenderId: '373638168139',
    projectId: 'prova-alex-6a2c5',
    authDomain: 'prova-alex-6a2c5.firebaseapp.com',
    storageBucket: 'prova-alex-6a2c5.firebasestorage.app',
    measurementId: 'G-SVY2NPG405',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgTDMTy-FYRK0YY4aSyuj595QHpc__vaE',
    appId: '1:373638168139:android:b558aa2dcf56d5ec6017ce',
    messagingSenderId: '373638168139',
    projectId: 'prova-alex-6a2c5',
    storageBucket: 'prova-alex-6a2c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDttlNzFcNw6edGQh15F9HlFL-EuCebNFc',
    appId: '1:373638168139:ios:a52681e0e2a82b7e6017ce',
    messagingSenderId: '373638168139',
    projectId: 'prova-alex-6a2c5',
    storageBucket: 'prova-alex-6a2c5.firebasestorage.app',
    iosBundleId: 'com.example.prova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDttlNzFcNw6edGQh15F9HlFL-EuCebNFc',
    appId: '1:373638168139:ios:a52681e0e2a82b7e6017ce',
    messagingSenderId: '373638168139',
    projectId: 'prova-alex-6a2c5',
    storageBucket: 'prova-alex-6a2c5.firebasestorage.app',
    iosBundleId: 'com.example.prova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSPDSOc0qnZbRakxJluaLqK7-xD0w1tiM',
    appId: '1:373638168139:web:84e2095a9e965f9d6017ce',
    messagingSenderId: '373638168139',
    projectId: 'prova-alex-6a2c5',
    authDomain: 'prova-alex-6a2c5.firebaseapp.com',
    storageBucket: 'prova-alex-6a2c5.firebasestorage.app',
    measurementId: 'G-6JRWS9RQKZ',
  );

}